### ISSUE TITLE
Error: libvips-cpp.so.42: cannot open shared object file

### ISSUE THREAD

**Issue by pronebird** [alex88/heroku-buildpack-vips#29]
Suddenly stopped working today. Any idea why?

```
2018-03-02T00:48:01.785967+00:00 app[web.1]: - $ node server.build/server.js
2018-03-02T00:48:02.639045+00:00 app[web.1]: - module.js:672
2018-03-02T00:48:02.639078+00:00 app[web.1]: -   return process.dlopen(module, path._makeLong(filename));
2018-03-02T00:48:02.639083+00:00 app[web.1]: - 
2018-03-02T00:48:02.639081+00:00 app[web.1]: -                  ^
2018-03-02T00:48:02.639085+00:00 app[web.1]: - Error: libvips-cpp.so.42: cannot open shared object file: No such file or directory
2018-03-02T00:48:02.639087+00:00 app[web.1]: -     at Object.Module._extensions..node (module.js:672:18)
2018-03-02T00:48:02.639090+00:00 app[web.1]: -     at tryModuleLoad (module.js:499:12)
2018-03-02T00:48:02.639092+00:00 app[web.1]: -     at Function.Module._load (module.js:491:3)
2018-03-02T00:48:02.639094+00:00 app[web.1]: -     at Module.require (module.js:587:17)
2018-03-02T00:48:02.639089+00:00 app[web.1]: -     at Module.load (module.js:556:32)
2018-03-02T00:48:02.639097+00:00 app[web.1]: -     at Object.<anonymous> (/app/node_modules/sharp/lib/constructor.js:10:15)
2018-03-02T00:48:02.639099+00:00 app[web.1]: -     at Module._compile (module.js:643:30)
2018-03-02T00:48:02.639095+00:00 app[web.1]: -     at require (internal/module.js:11:18)
2018-03-02T00:48:02.639100+00:00 app[web.1]: -     at Object.Module._extensions..js (module.js:654:10)
2018-03-02T00:48:02.639103+00:00 app[web.1]: -     at tryModuleLoad (module.js:499:12)
2018-03-02T00:48:02.639105+00:00 app[web.1]: -     at Function.Module._load (module.js:491:3)
2018-03-02T00:48:02.639102+00:00 app[web.1]: -     at Module.load (module.js:556:32)
2018-03-02T00:48:02.639109+00:00 app[web.1]: -     at Object.<anonymous> (/app/node_modules/sharp/lib/index.js:3:15)
2018-03-02T00:48:02.639108+00:00 app[web.1]: -     at require (internal/module.js:11:18)
2018-03-02T00:48:02.639111+00:00 app[web.1]: -     at Module._compile (module.js:643:30)
2018-03-02T00:48:02.639106+00:00 app[web.1]: -     at Module.require (module.js:587:17)

```

**Comment by apavlyut** [comment]
+

**Comment by rmckeel** [comment]
This might be related to https://github.com/lovell/sharp/issues/186.  If so, it seems that v0.20.0+ will have a 'prebuild' that could resolve your issue.

Also, I have noted that this is an intermittent issue.  Which to me means that a new commit or an empty commit like below may clear up the issue.  I prefer upgrading and see if that solves it ;)

```
git commit --allow-empty -m "force Heroku rebuild"
git push heroku master
```

UPDATE: updating package.json to use sharp@0.20.8 (the latest as of today) did not resolve the intermittent issue with my Heroku instance.  Note I am not using heroku-buildpack-vips, I just thought this discussion might be relevant/helpful to this thread.  Sorry I don't have better news.
